[pytest]
DJANGO_SETTINGS_MODULE = ocean.settings
; python_files = tests/*.py tests/**/*.py
; python_classes = Test*
; python_functions = test_*
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --reuse-db
    -v
