"""
Django settings for ocean project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from ocean.settings.dev import *

# BASE_DIR = Path(__file__).resolve().parent.parent.parent


SECRET_KEY = os.environ["OCEAN_SECRET_KEY"]

DEBUG = False

ALLOWED_HOSTS = os.environ["OCEAN_ALLOWED_HOSTS"].split(" ")

CORS_ORIGIN_WHITELIST = os.environ["OCEAN_CORS_OROGIN_WHITELIST"].split(" ")

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["OCEAN_DB_NAME"],
        "USER": os.environ["OCEAN_DB_USER"],
        "PASSWORD": os.environ["OCEAN_DB_PASSWORD"],
        "HOST": os.environ["OCEAN_DB_HOST"],
        "PORT": os.environ["OCEAN_DB_PORT"],
    }
}


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
