# Generated by Django 6.0.2 on 2026-03-16 02:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.UUIDField(default=uuid.uuid7, unique=True),
        ),
    ]
