# Generated by Django 6.0.2 on 2026-02-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="extra",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
