# Generated by Django 6.0.2 on 2026-02-22 05:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0002_alter_page_extra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="content",
        ),
        migrations.AddField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid7)),
                ("content", models.TextField()),
                (
                    "next",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="prev", to="page.block"
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="blocks", to="page.page"
                    ),
                ),
            ],
        ),
    ]
