# Generated by Django 6.0.2 on 2026-02-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_remove_page_content_page_slug_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, max_length=127),
        ),
    ]
