# Generated by Django 6.0.2 on 2026-02-28 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0004_alter_page_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="previous",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="next_block", to="page.block"
            ),
        ),
        migrations.AlterField(
            model_name="block",
            name="next",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="previous_block", to="page.block"
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("page", "next"), name="page_next_unique_together", nulls_distinct=True
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("page", "previous"), name="page_previous_unique_together", nulls_distinct=True
            ),
        ),
    ]
