# Generated by Django 6.0.2 on 2026-03-16 02:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0005_block_previous_alter_block_next_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="uid",
            field=models.UUIDField(default=uuid.uuid7, unique=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="uid",
            field=models.UUIDField(default=uuid.uuid7, unique=True),
        ),
    ]
