# Generated by Django 6.0.2 on 2026-03-16 02:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0006_alter_block_uid_alter_page_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="block",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="block",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="block",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
