# Generated by Django 6.0.2 on 2026-03-22 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_remove_block_previous_alter_block_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='starts_page', to='page.block'),
        ),
    ]
