# Generated by Django 6.0.2 on 2026-03-22 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0010_page_first_block"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE page_block 
                DROP CONSTRAINT IF EXISTS page_block_next_id_key;
            """,
            reverse_sql="""
                ALTER TABLE page_block 
                ADD CONSTRAINT IF NOT EXISTS page_block_next_id_key 
                UNIQUE (next_id);
            """,
        )
    ]
