# Generated by Django 6.0.2 on 2026-03-22 07:38

import django.db.models.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0011_rm_block_next_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="next",
            field=models.OneToOneField(
                db_constraint=False,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous",
                to="page.block",
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("next",),
                name="unique_block_next",
            ),
        ),
    ]
