# Generated by Django 6.0.2 on 2026-03-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_alter_block_next_block_unique_block_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
